language: node_js
node_js:
  - "6.1"
services:
  - mysql
before_install:
  - mysql -e "DROP DATABASE IF EXISTS gitlog;"
  - mysql -e "CREATE DATABASE gitlog;"
  - mysql -e "USE gitlog"
  - mysql -e "CREATE TABLE gitlog.repositorios (
    pk INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NULL,
    endereco VARCHAR(255) NULL,
    PRIMARY KEY (pk));"
  - mysql -u root -e "GRANT USAGE ON gitlog.repositorios TO gitlog@localhost;"  
  - mysql -u root -e "DROP USER gitlog@localhost;"
  - mysql -u root -e "CREATE USER gitlog@localhost IDENTIFIED BY 'gitlog*' ;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON gitlog.repositorios TO gitlog@localhost;"
